#include "busenum.h"
#include <wdmsec.h>
#include <usb.h>
#include <usbiodef.h>
#include <usbbusif.h>

#ifdef ALLOC_PRAGMA
#pragma alloc_text(PAGE, Bus_CreatePdo)
#pragma alloc_text(PAGE, Bus_EvtDeviceListCreatePdo)
#pragma alloc_text(PAGE, Bus_EvtDevicePrepareHardware)
#pragma alloc_text(PAGE, RawPdo_EvtIoDeviceControl)
#pragma alloc_text(PAGE, RawPdo_EvtIoInternalDeviceControl)
#pragma alloc_text(PAGE, RawPdo_EvtIoDefault)
#pragma alloc_text(PAGE, Pdo_ProcessQueryInterfaceRequest)
#endif

NTSTATUS Bus_EvtDeviceListCreatePdo(
    WDFCHILDLIST DeviceList,
    PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER IdentificationDescription,
    PWDFDEVICE_INIT ChildInit)
{
    PPDO_IDENTIFICATION_DESCRIPTION pDesc;

    PAGED_CODE();

    pDesc = CONTAINING_RECORD(IdentificationDescription, PDO_IDENTIFICATION_DESCRIPTION, Header);

    return Bus_CreatePdo(WdfChildListGetDevice(DeviceList), ChildInit, pDesc->SerialNo, pDesc->TargetType);
}

NTSTATUS Bus_CreatePdo(
    _In_ WDFDEVICE Device,
    _In_ PWDFDEVICE_INIT DeviceInit,
    _In_ ULONG SerialNo,
    _In_ VIGEM_TARGET_TYPE TargetType)
{
    NTSTATUS status;
    PPDO_DEVICE_DATA pdoData;
    WDFDEVICE hChild = NULL;
    WDF_DEVICE_PNP_CAPABILITIES pnpCaps;
    WDF_DEVICE_POWER_CAPABILITIES powerCaps;
    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks;
    WDF_OBJECT_ATTRIBUTES pdoAttributes;
    WDF_IO_QUEUE_CONFIG  ioQueueConfig;
    WDFQUEUE queue;
    DECLARE_CONST_UNICODE_STRING(deviceLocation, L"Virtual Gamepad Emulation Bus");
    DECLARE_UNICODE_STRING_SIZE(buffer, MAX_INSTANCE_ID_LEN);
    // reserve space for device id
    DECLARE_UNICODE_STRING_SIZE(deviceId, MAX_INSTANCE_ID_LEN);
    // reserve space for device description
    DECLARE_UNICODE_STRING_SIZE(deviceDescription, MAX_DEVICE_DESCRIPTION_LEN);


    PAGED_CODE();

    UNREFERENCED_PARAMETER(Device);

    KdPrint(("Entered Bus_CreatePdo\n"));

    // set device type
    WdfDeviceInitSetDeviceType(DeviceInit, FILE_DEVICE_BUS_EXTENDER);

    // enter RAW device mode
    {
        status = WdfPdoInitAssignRawDevice(DeviceInit, &GUID_DEVCLASS_VIGEM_RAWPDO);
        if (!NT_SUCCESS(status))
        {
            KdPrint(("WdfPdoInitAssignRawDevice failed status 0x%x\n", status));
            return status;
        }

        WdfDeviceInitSetCharacteristics(DeviceInit, FILE_AUTOGENERATED_DEVICE_NAME, TRUE);

        status = WdfDeviceInitAssignSDDLString(DeviceInit, &SDDL_DEVOBJ_SYS_ALL_ADM_RWX_WORLD_RWX_RES_RWX);
        if (!NT_SUCCESS(status))
        {
            KdPrint(("WdfDeviceInitAssignSDDLString failed status 0x%x\n", status));
            return status;
        }
    }

    // set parameters matching desired target device
    switch (TargetType)
    {
        //
        // A Xbox 360 device was requested
        // 
    case Xbox360Wired:
    {
        // set device description
        {
            // prepare device description
            status = RtlUnicodeStringPrintf(&deviceDescription, L"Virtual Xbox 360 Controller");
            if (!NT_SUCCESS(status)) {
                return status;
            }
        }

        // set hardware ids
        {
            RtlUnicodeStringPrintf(&buffer, L"USB\\VID_045E&PID_028E&REV_0114");

            RtlUnicodeStringCopy(&deviceId, &buffer);

            status = WdfPdoInitAddHardwareID(DeviceInit, &buffer);
            if (!NT_SUCCESS(status)) {
                return status;
            }

            RtlUnicodeStringPrintf(&buffer, L"USB\\VID_045E&PID_028E");

            status = WdfPdoInitAddHardwareID(DeviceInit, &buffer);
            if (!NT_SUCCESS(status)) {
                return status;
            }
        }

        // set compatible ids
        {
            RtlUnicodeStringPrintf(&buffer, L"USB\\MS_COMP_XUSB10");

            status = WdfPdoInitAddCompatibleID(DeviceInit, &buffer);
            if (!NT_SUCCESS(status)) {
                return status;
            }

            RtlUnicodeStringPrintf(&buffer, L"USB\\Class_FF&SubClass_5D&Prot_01");

            status = WdfPdoInitAddCompatibleID(DeviceInit, &buffer);
            if (!NT_SUCCESS(status)) {
                return status;
            }

            RtlUnicodeStringPrintf(&buffer, L"USB\\Class_FF&SubClass_5D");

            status = WdfPdoInitAddCompatibleID(DeviceInit, &buffer);
            if (!NT_SUCCESS(status)) {
                return status;
            }

            RtlUnicodeStringPrintf(&buffer, L"USB\\Class_FF");

            status = WdfPdoInitAddCompatibleID(DeviceInit, &buffer);
            if (!NT_SUCCESS(status)) {
                return status;
            }
        }
    }
    break;
    //
    // A Sony DualShock 4 device was requested
    // 
    case DualShock4Wired:
    {
        // set device description
        {
            // prepare device description
            status = RtlUnicodeStringPrintf(&deviceDescription, L"Virtual DualShock 4 Controller");
            if (!NT_SUCCESS(status)) {
                return status;
            }
        }

        // set hardware ids
        {
            RtlUnicodeStringPrintf(&buffer, L"USB\\VID_054C&PID_05C4&REV_0100");

            RtlUnicodeStringCopy(&deviceId, &buffer);

            status = WdfPdoInitAddHardwareID(DeviceInit, &buffer);
            if (!NT_SUCCESS(status)) {
                return status;
            }

            RtlUnicodeStringPrintf(&buffer, L"USB\\VID_054C&PID_05C4");

            status = WdfPdoInitAddHardwareID(DeviceInit, &buffer);
            if (!NT_SUCCESS(status)) {
                return status;
            }
        }
    }
    break;
    }

    // set device id
    status = WdfPdoInitAssignDeviceID(DeviceInit, &deviceId);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    // prepare instance id
    status = RtlUnicodeStringPrintf(&buffer, L"%02d", SerialNo);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    // set instance id
    status = WdfPdoInitAssignInstanceID(DeviceInit, &buffer);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    // set device description (for English operating systems)
    status = WdfPdoInitAddDeviceText(DeviceInit, &deviceDescription, &deviceLocation, 0x409);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    // default locale is English
    WdfPdoInitSetDefaultLocale(DeviceInit, 0x409);

    // PNP/Power event callbacks
    {
        WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);

        pnpPowerCallbacks.EvtDevicePrepareHardware = Bus_EvtDevicePrepareHardware;
        pnpPowerCallbacks.EvtDeviceD0Entry = Bus_EvtDeviceD0Entry;

        WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);
    }

    WdfPdoInitAllowForwardingRequestToParent(DeviceInit);

    // Create PDO
    {
        WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&pdoAttributes, PDO_DEVICE_DATA);

        status = WdfDeviceCreate(&DeviceInit, &pdoAttributes, &hChild);
        if (!NT_SUCCESS(status))
        {
            return status;
        }
    }

    // Expose USB interface
    {
        status = WdfDeviceCreateDeviceInterface(Device, (LPGUID)&GUID_DEVINTERFACE_USB_DEVICE, NULL);
        if (!NT_SUCCESS(status))
        {
            KdPrint(("WdfDeviceCreateDeviceInterface failed status 0x%x\n", status));
            return status;
        }
    }

    // Set PDO properties
    {
        pdoData = PdoGetData(hChild);

        pdoData->SerialNo = SerialNo;
        pdoData->TargetType = TargetType;
        pdoData->OwnerProcessId = CURRENT_PROCESS_ID();
    }

    // I/O queue setup
    {
        WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&ioQueueConfig, WdfIoQueueDispatchSequential);

        ioQueueConfig.EvtIoDefault = RawPdo_EvtIoDefault;
        ioQueueConfig.EvtIoDeviceControl = RawPdo_EvtIoDeviceControl;
        ioQueueConfig.EvtIoInternalDeviceControl = RawPdo_EvtIoInternalDeviceControl;
    }

    // Create PDO
    {
        status = WdfIoQueueCreate(hChild, &ioQueueConfig, WDF_NO_OBJECT_ATTRIBUTES, &queue);
        if (!NT_SUCCESS(status))
        {
            KdPrint(("WdfIoQueueCreate failed 0x%x\n", status));
            return status;
        }
    }

    // PNP capabilities
    {
        WDF_DEVICE_PNP_CAPABILITIES_INIT(&pnpCaps);

        pnpCaps.Removable = WdfTrue;
        pnpCaps.EjectSupported = WdfTrue;
        pnpCaps.SurpriseRemovalOK = WdfTrue;

        pnpCaps.Address = SerialNo;
        pnpCaps.UINumber = SerialNo;

        WdfDeviceSetPnpCapabilities(hChild, &pnpCaps);
    }

    // Power capabilities
    {
        WDF_DEVICE_POWER_CAPABILITIES_INIT(&powerCaps);

        powerCaps.DeviceD1 = WdfTrue;
        powerCaps.WakeFromD1 = WdfTrue;
        powerCaps.DeviceWake = PowerDeviceD1;

        powerCaps.DeviceState[PowerSystemWorking] = PowerDeviceD0;
        powerCaps.DeviceState[PowerSystemSleeping1] = PowerDeviceD1;
        powerCaps.DeviceState[PowerSystemSleeping2] = PowerDeviceD3;
        powerCaps.DeviceState[PowerSystemSleeping3] = PowerDeviceD3;
        powerCaps.DeviceState[PowerSystemHibernate] = PowerDeviceD3;
        powerCaps.DeviceState[PowerSystemShutdown] = PowerDeviceD3;

        WdfDeviceSetPowerCapabilities(hChild, &powerCaps);
    }

    return status;
}

_Use_decl_annotations_
NTSTATUS
Pdo_ProcessQueryInterfaceRequest(
    WDFDEVICE  Device,
    LPGUID  InterfaceType,
    PINTERFACE  ExposedInterface,
    PVOID  ExposedInterfaceSpecificData
)
{
    UNREFERENCED_PARAMETER(ExposedInterfaceSpecificData);

    PAGED_CODE();

    // Validate requested interface type
    if (IsEqualGUID(InterfaceType, (PVOID)&USB_BUS_INTERFACE_USBDI_GUID))
    {
        KdPrint(("USB_BUS_INTERFACE_USBDI_GUID : Version %d Requested\n", ExposedInterface->Version));

        auto eiVersion = ExposedInterface->Version;
        auto eiSize = ExposedInterface->Size;

        // Validate queried interface version and size
        if ((eiVersion != USB_BUSIF_USBDI_VERSION_0 && eiVersion != USB_BUSIF_USBDI_VERSION_1)
            || (eiVersion == USB_BUSIF_USBDI_VERSION_0 && eiSize < sizeof(USB_BUS_INTERFACE_USBDI_V0))
            || (eiVersion == USB_BUSIF_USBDI_VERSION_1 && eiSize < sizeof(USB_BUS_INTERFACE_USBDI_V1)))
        {
            return STATUS_INVALID_PARAMETER;
        }

        PUSB_BUS_INTERFACE_USBDI_V1 pInterface = (PUSB_BUS_INTERFACE_USBDI_V1)ExposedInterface;

        pInterface->BusContext = Device;

        pInterface->InterfaceReference = WdfDeviceInterfaceReferenceNoOp;
        pInterface->InterfaceDereference = WdfDeviceInterfaceDereferenceNoOp;

        switch (eiVersion)
        {
        case USB_BUSIF_USBDI_VERSION_1:
            pInterface->IsDeviceHighSpeed = UsbPdo_IsDeviceHighSpeed;
            break;
        }
    }
    else
    {
        KdPrint(("Pdo_ProcessQueryInterfaceRequest called for interface GUID: %08X-%04X-%04X-%02X%02X%02X%02X%02X%02X%02X%02X\n",
            InterfaceType->Data1,
            InterfaceType->Data2,
            InterfaceType->Data3,
            InterfaceType->Data4[0],
            InterfaceType->Data4[1],
            InterfaceType->Data4[2],
            InterfaceType->Data4[3],
            InterfaceType->Data4[4],
            InterfaceType->Data4[5],
            InterfaceType->Data4[6],
            InterfaceType->Data4[7]));
    }

    return STATUS_SUCCESS;
}

NTSTATUS Bus_EvtDevicePrepareHardware(
    _In_ WDFDEVICE    Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated
)
{
    WDF_QUERY_INTERFACE_CONFIG ifaceCfg;
    NTSTATUS status;

    PAGED_CODE();

    UNREFERENCED_PARAMETER(ResourcesRaw);
    UNREFERENCED_PARAMETER(ResourcesTranslated);

    KdPrint(("Bus_EvtDevicePrepareHardware: 0x%p\n", Device));

    // Expose USB interface
    {
        INTERFACE dummyIface;

        dummyIface.Size = sizeof(INTERFACE);
        dummyIface.Version = 1;
        dummyIface.Context = (PVOID)Device;

        dummyIface.InterfaceReference = WdfDeviceInterfaceReferenceNoOp;
        dummyIface.InterfaceDereference = WdfDeviceInterfaceDereferenceNoOp;

        //
        // Dummy 0
        // 
        WDF_QUERY_INTERFACE_CONFIG_INIT(&ifaceCfg, (PINTERFACE)&dummyIface, &GUID_DEVINTERFACE_XUSB_UNKNOWN_0, Pdo_ProcessQueryInterfaceRequest);

        status = WdfDeviceAddQueryInterface(Device, &ifaceCfg);
        if (!NT_SUCCESS(status))
        {
            KdPrint(("Couldn't register unknown interface GUID: %08X-%04X-%04X-%02X%02X%02X%02X%02X%02X%02X%02X (status 0x%x)\n",
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data1,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data2,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data3,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data4[0],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data4[1],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data4[2],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data4[3],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data4[4],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data4[5],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data4[6],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_0.Data4[7],
                status));

            return status;
        }

        //
        // Dummy 1
        // 
        WDF_QUERY_INTERFACE_CONFIG_INIT(&ifaceCfg, (PINTERFACE)&dummyIface, &GUID_DEVINTERFACE_XUSB_UNKNOWN_1, Pdo_ProcessQueryInterfaceRequest);

        status = WdfDeviceAddQueryInterface(Device, &ifaceCfg);
        if (!NT_SUCCESS(status))
        {
            KdPrint(("Couldn't register unknown interface GUID: %08X-%04X-%04X-%02X%02X%02X%02X%02X%02X%02X%02X (status 0x%x)\n",
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data1,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data2,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data3,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data4[0],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data4[1],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data4[2],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data4[3],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data4[4],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data4[5],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data4[6],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_1.Data4[7],
                status));

            return status;
        }

        //
        // Dummy 2
        // 
        WDF_QUERY_INTERFACE_CONFIG_INIT(&ifaceCfg, (PINTERFACE)&dummyIface, &GUID_DEVINTERFACE_XUSB_UNKNOWN_2, Pdo_ProcessQueryInterfaceRequest);

        status = WdfDeviceAddQueryInterface(Device, &ifaceCfg);
        if (!NT_SUCCESS(status))
        {
            KdPrint(("Couldn't register unknown interface GUID: %08X-%04X-%04X-%02X%02X%02X%02X%02X%02X%02X%02X (status 0x%x)\n",
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data1,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data2,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data3,
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data4[0],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data4[1],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data4[2],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data4[3],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data4[4],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data4[5],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data4[6],
                GUID_DEVINTERFACE_XUSB_UNKNOWN_2.Data4[7],
                status));

            return status;
        }

        USB_BUS_INTERFACE_USBDI_V1 pInterface;

        pInterface.Size = sizeof(USB_BUS_INTERFACE_USBDI_V1);
        pInterface.Version = USB_BUSIF_USBDI_VERSION_1;
        pInterface.BusContext = (PVOID)Device;

        pInterface.InterfaceReference = WdfDeviceInterfaceReferenceNoOp;
        pInterface.InterfaceDereference = WdfDeviceInterfaceDereferenceNoOp;

        WDF_QUERY_INTERFACE_CONFIG_INIT(&ifaceCfg, (PINTERFACE)&pInterface, &USB_BUS_INTERFACE_USBDI_GUID, Pdo_ProcessQueryInterfaceRequest);

        status = WdfDeviceAddQueryInterface(Device, &ifaceCfg);
        if (!NT_SUCCESS(status))
        {
            KdPrint(("WdfDeviceAddQueryInterface failed status 0x%x\n", status));
            return status;
        }
    }

    return status;
}

NTSTATUS Bus_EvtDeviceD0Entry(
    _In_ WDFDEVICE              Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState
)
{
    UNREFERENCED_PARAMETER(PreviousState);

    KdPrint(("Bus_EvtDeviceD0Entry: 0x%p\n", Device));

    return STATUS_SUCCESS;
}

VOID RawPdo_EvtIoDeviceControl(
    _In_ WDFQUEUE   Queue,
    _In_ WDFREQUEST Request,
    _In_ size_t     OutputBufferLength,
    _In_ size_t     InputBufferLength,
    _In_ ULONG      IoControlCode
)
{
    UNREFERENCED_PARAMETER(Queue);
    UNREFERENCED_PARAMETER(Request);
    UNREFERENCED_PARAMETER(OutputBufferLength);
    UNREFERENCED_PARAMETER(InputBufferLength);
    UNREFERENCED_PARAMETER(IoControlCode);

    KdPrint(("RawPdo_EvtIoDeviceControl called\n"));
}

VOID RawPdo_EvtIoInternalDeviceControl(
    _In_ WDFQUEUE   Queue,
    _In_ WDFREQUEST Request,
    _In_ size_t     OutputBufferLength,
    _In_ size_t     InputBufferLength,
    _In_ ULONG      IoControlCode
)
{
    UNREFERENCED_PARAMETER(Queue);
    // UNREFERENCED_PARAMETER(Request);
    UNREFERENCED_PARAMETER(OutputBufferLength);
    UNREFERENCED_PARAMETER(InputBufferLength);
    UNREFERENCED_PARAMETER(IoControlCode);

    KdPrint(("RawPdo_EvtIoInternalDeviceControl called\n"));

    WdfRequestCompleteWithInformation(Request, STATUS_SUCCESS, 0);
}

VOID RawPdo_EvtIoDefault(
    _In_ WDFQUEUE   Queue,
    _In_ WDFREQUEST Request
)
{
    UNREFERENCED_PARAMETER(Queue);
    UNREFERENCED_PARAMETER(Request);

    KdPrint(("RawPdo_EvtIoDefault called\n"));
}
