//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nefarius.ViGEm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nefarius.ViGEm.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied target device is already plugged in..
        /// </summary>
        internal static string VigemAlreadyConnectedException {
            get {
                return ResourceManager.GetString("VigemAlreadyConnectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Virtual Gamepad Emulation Bus wasn&apos;t found. Please verify that the bus driver is installed and working properly..
        /// </summary>
        internal static string VigemBusNotFoundException {
            get {
                return ResourceManager.GetString("VigemBusNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bus is currently full and can&apos;t add more devices..
        /// </summary>
        internal static string VigemNoFreeSlotException {
            get {
                return ResourceManager.GetString("VigemNoFreeSlotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied target device couldn&apos;t get unplugged due to an unknown failure..
        /// </summary>
        internal static string VigemRemovalFailedException {
            get {
                return ResourceManager.GetString("VigemRemovalFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied target object isn&apos;t currently plugged in..
        /// </summary>
        internal static string VigemTargetNotPluggedInException {
            get {
                return ResourceManager.GetString("VigemTargetNotPluggedInException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target device object wasn&apos;t initialized properly..
        /// </summary>
        internal static string VigemTargetUninitializedException {
            get {
                return ResourceManager.GetString("VigemTargetUninitializedException", resourceCulture);
            }
        }
    }
}
